CXX         = c++
CXXLINKER   = $(CXX)
OPTFLAGS    = -Ofast
LIBS        = -L/opt/cuda/12.1/lib64 -lOpenCL -lm

CXXFLAGS    = -I/opt/cuda/12.1/include $(OPTFLAGS)

OBJ=o
RM=@rm -f

EXE=jac_solv
JAC_OBJ=jac_solv.o

all: $(EXE)

jac_solv: $(JAC_OBJ)
	$(CXXLINKER) $(CXXFLAGS) -o jac_solv $(JAC_OBJ) $(LIBS)

clean:
	$(RM) $(EXES) *.o *.ptx *.cub

.SUFFIXES:
.SUFFIXES: .cxx .o

.cxx.o:
	$(CXX) $(CXXFLAGS) -c $<
