CXX         = c++
CXXLINKER   = $(CXX)
OPTFLAGS    = -Ofast
LIBS        = -L/opt/cuda/12.1/lib64 -lOpenGL -lm

CXXFLAGS    = -I/opt/cuda/12.1/include $(OPTFLAGS)

OBJ=o
RM=@rm -f

EXES=jac_solv
JAC_OBJS  = jac_solv.$(OBJ)

all: $(EXES)

jac_solv: $(JAC_OBJS)
	$(CXXLINKER) $(CXXFLAGS) -o jac_solv $(JAC_OBJS) $(LIBS)

clean:
	$(RM) $(EXES) *.$(OBJ) *.ptx *.cub

.SUFFIXES:
.SUFFIXES: .cxx .$(OBJ)

.cxx.$(OBJ):
	$(CXX) $(CXXFLAGS) -c $<
