NVCC        = nvcc
NVCCLINKER  = $(NVCC)
OPTFLAGS    = -Xptxas=-O4,-opt-fp-atomics,-v -Xcompiler=-fopenmp,-g0,-Ofast -O4 -dopt=on -dlto -gen-opt-lto -use_fast_math -extra-device-vectorization
LIBS        = -lm

NVCCFLAGS   = $(OPTFLAGS)

OBJ=o
RM=@rm -f

EXE=jac_solv
JAC_OBJ=jac_solv.o

all: $(EXE)

jac_solv: $(JAC_OBJ)
	$(NVCCLINKER) $(NVCCFLAGS) -o jac_solv $(JAC_OBJ) $(LIBS)

clean:
	$(RM) $(EXE) *.o *.ptx *.cub

.SUFFIXES:
.SUFFIXES: .cu .o

.cu.o:
	$(NVCC) $(NVCCFLAGS) -c $<
